name: niceo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^4.4.0

  flutter_secure_storage: ^8.0.0

  google_sign_in: ^6.1.0
  sign_in_with_apple: ^7.0.1

  # API bağlantısı için
  http: ^1.1.0
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  intl: ^0.20.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/niceo.png"

flutter:
  uses-material-design: true




  